### ISSUE TITLE
树莓派4B+ 官方Raspbian + docker 运行报错

### ISSUE THREAD

**Issue by breakersun** [changfeng2021/cf-clash#2]
报错信息如下：

,
  .   ____          _            __ _ _,
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \,
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \,
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) ),
  '  |____| .__|_| |_|_| |_\__, | / / / /,
 =========|_|==============|___/=/_/_/_/,
 :: Spring Boot ::                (v2.6.6),
,
2022-06-06 05:58:55.903  INFO 1 --- [           main] com.v2rayse.clash.ClashApplication       : Starting ClashApplication using Java 11.0.15 on RPi4 with PID 1 (/opt/app/cf-clash.jar started by root in /),
2022-06-06 05:58:55.917  INFO 1 --- [           main] com.v2rayse.clash.ClashApplication       : No active profile set, falling back to 1 default profile: "default",
2022-06-06 05:59:01.253  WARN 1 --- [           main] io.undertow.websockets.jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used,
2022-06-06 05:59:01.346  INFO 1 --- [           main] io.undertow.servlet                      : Initializing Spring embedded WebApplicationContext,
2022-06-06 05:59:01.347  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 5121 ms,
2022-06-06 05:59:03.266  INFO 1 --- [           main] o.s.b.a.w.s.WelcomePageHandlerMapping    : Adding welcome page: class path resource [public/index.html],
2022-06-06 05:59:03.701  INFO 1 --- [           main] io.undertow                              : starting server: Undertow - 2.2.16.Final,
2022-06-06 05:59:03.735  INFO 1 --- [           main] org.xnio                                 : XNIO version 3.8.6.Final,
2022-06-06 05:59:03.793  INFO 1 --- [           main] org.xnio.nio                             : XNIO NIO Implementation Version 3.8.6.Final,
2022-06-06 05:59:04.226  INFO 1 --- [           main] org.jboss.threads                        : JBoss Threads version 3.1.0.Final,
2022-06-06 05:59:04.389  INFO 1 --- [           main] o.s.b.w.e.undertow.UndertowWebServer     : Undertow started on port(s) 8443 (http),
2022-06-06 05:59:04.427  INFO 1 --- [           main] s.a.ScheduledAnnotationBeanPostProcessor : No TaskScheduler/ScheduledExecutorService bean found for scheduled processing,
2022-06-06 05:59:04.466  INFO 1 --- [           main] com.v2rayse.clash.ClashApplication       : Started ClashApplication in 11.019 seconds (JVM running for 13.401),
2022-06-06 05:59:04.493  INFO 1 --- [           main] com.v2rayse.clash.utils.DirectoryUtil    : Clash Home Checked. true,
2022-06-06 05:59:04.499  INFO 1 --- [           main] com.v2rayse.clash.utils.DirectoryUtil    : Temp Folder Checked. true,
2022-06-06 05:59:04.601  INFO 1 --- [           main] com.v2rayse.clash.onload.ClashOnLoad     : Config json file checked. true,
2022-06-06 05:59:04.792  INFO 1 --- [           main] com.v2rayse.clash.utils.DirectoryUtil    : Country.mmdb copy completed!,
2022-06-06 05:59:04.802  INFO 1 --- [           main] ConditionEvaluationReportLoggingListener : ,
,
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.,
2022-06-06 05:59:04.900 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed,
,
java.lang.IllegalStateException: Failed to execute CommandLineRunner,
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:780) ~[spring-boot-2.6.6.jar!/:2.6.6],
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:761) ~[spring-boot-2.6.6.jar!/:2.6.6],
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:310) ~[spring-boot-2.6.6.jar!/:2.6.6],
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1312) ~[spring-boot-2.6.6.jar!/:2.6.6],
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301) ~[spring-boot-2.6.6.jar!/:2.6.6],
	at com.v2rayse.clash.ClashApplication.main(ClashApplication.java:14) ~[classes!/:na],
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na],
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na],
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na],
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na],
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[cf-clash.jar:na],
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[cf-clash.jar:na],
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[cf-clash.jar:na],
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[cf-clash.jar:na],
Caused by: cn.hutool.core.io.resource.NoResourceException: Resource of path [clash/linux/null/clash] not exist!,
	at cn.hutool.core.io.resource.ClassPathResource.initUrl(ClassPathResource.java:122) ~[hutool-all-5.8.0.M1.jar!/:na],
	at cn.hutool.core.io.resource.ClassPathResource.<init>(ClassPathResource.java:74) ~[hutool-all-5.8.0.M1.jar!/:na],
	at cn.hutool.core.io.resource.ClassPathResource.<init>(ClassPathResource.java:34) ~[hutool-all-5.8.0.M1.jar!/:na],
	at com.v2rayse.clash.utils.DirectoryUtil.clashCheck(DirectoryUtil.java:99) ~[classes!/:na],
	at com.v2rayse.clash.onload.ClashOnLoad.run(ClashOnLoad.java:19) ~[classes!/:na],
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:777) ~[spring-boot-2.6.6.jar!/:2.6.6],
	... 13 common frames omitted,
,
2022-06-06 05:59:04.919  INFO 1 --- [           main] io.undertow                              : stopping server: Undertow - 2.2.16.Final,

**Comment by changfeng2021** [comment]
没有找到资源文件，我对镜像做了更新，你去 pull 一下。可以在程序判断不准确没有获取 `clash` 程序情况下，可以自行上传

**Comment by breakersun** [comment]
使用树莓派4b + 官方64bit系统 + 官方docker，实测成功。感谢。
